### PR TITLE
CKV_AZURE_127/CKV_AZURE_128

### PR DESCRIPTION
**Pull request by milkanas**
CKV_AZURE_127 - Ensure that My SQL server enables Threat detection policy
CKV_AZURE_128 - Ensure that Postgres SQL server enables Threat detection policy
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by rotemavni — CHANGES_REQUESTED** [review]
@milkanas Can you please add test cases for when the inspected key doesn't exist?

**Comment by milkanas** [comment]
> @milkanas Can you please add test cases for when the inspected key doesn't exist?

No but, you are right it was almost the same check 10 copies

**Comment by rotemavni** [comment]
> No but, you are right it was almost the same check 10 copies with different keys

@milkanas Sorry I don't understand the response.. Why can't you add the test cases?

**Comment by milkanas** [comment]
> > No but, you are right it was almost the same check 10 copies with different keys
> 
> @milkanas Sorry I don't understand the response.. Why can't you add the test cases?

My bad (answered about something else ) ... yep of course

**Review by rotemavni — APPROVED** [review]

**Pull request merged**
